### ISSUE TITLE
[BUG?] setTextAlign a nil value

### ISSUE THREAD

**Issue by piprett** [Pyroxenium/Basalt#11]
The function documented [here, "setTextAlign" ](https://github.com/Pyroxenium/Basalt/wiki/Object#settextalign) is nil.
How to replicate:
```
local basalt = dofile("lib/basalt")
local mainFrame = basalt.createFrame("mainFrame"):show()
local label = mainFrame:addLabel("label"):setSize(45,1):setValue("This is a label"):setTextAlign("center","center"):show()
basalt.autoUpdate()
````
This errors: `test.lua:3: attempt to call method 'setTextAlign' (a nil value)`

It seems it's on Button, not Object?

**Comment by NoryiE** [comment]
Hey!

Thanks you. Sadly i have to say the setTextAlign is wrong placed in the objects page. Because obviously not all of the objects do have text which can get centered. I will have to change this in the wiki page's. Labels don't have a setTextAlign function yet.

BUT the idea is actually pretty nice. So i decided to implement it quick. The last version should have setTextAlign(horizontal, vertical) for labels. If something doesn't work correct just tell me!
