### ISSUE TITLE
[FEATURE REQUEST] Bigfont

### ISSUE THREAD

**Issue by piprett** [Pyroxenium/Basalt#12]
**Type**: Feature request

Hey,

I think it would be cool if we could implement something like [Bigfont by Wojbie](http://www.computercraft.info/forums2/index.php?/topic/25367-bigfont-api-write-bigger-letters-v10/) or something similar for labels.
I have an example of BigFont beeing used, see image below:
![image](https://user-images.githubusercontent.com/49862976/170814249-0abb5663-1532-47a7-90ec-5df67271f8a8.png)
Here you can see the "PixelTech INC" sized big, using BigFont, and under the "maybe?", using normal text.

I can imagine the api to be something like this:
`label:setFontSize(font size)`, where font size is 1 for normal, 2 for bigger, 3 for even bigger, etc, etc.

**Comment by NoryiE** [comment]
Hey hey, i am currently working on that feature. It seems like i wont finish it today. I'm having some smaller issues with centering the bigfont sized text. However, the api itself is already implemented, the textsize also gets bigger (1, 2, 3 by bigfont is currently supported)
It's always a challenge to implement such apis because i always have to remake the drawing system (because i am using a custom one).

On the bigfont api page i also saw blittle support. Basalt already supports blittle. If you want a fast solution you could check out the image object and use the makeBlittleText(nSize,sString,nTextColor,nBackgroundColor) by bigfont.

Also - another very nice idea! Thank you very much. Probably tomorrow i will have finished the fontsize feature for labels.

**Comment by NoryiE** [comment]
The last version should have bigfonts now implemented. It is not the full library. Currently only labels support bigfonts. I am not sure if i want to extend this feature to other objects, it would be quite some work to do so.

The method to call would be label:setFontSize(size), 1 is the default text size, 2, 3 and 4 are the bigfonts sizes by bigfont. I am currently not thinking about implementing bigger sizes.
