### ISSUE TITLE
bug: Key press transfers to the next Input when `setFocus` in used inside `onKey`

### ISSUE THREAD

**Issue by luiz00martins** [Pyroxenium/Basalt#30]
_Note: I'm not sure if this is a bug or expected behaviour._

**Describe the bug**

Say you have inputs A and B. If you use `B:setFocus()` inside of `A:onKey`, pressing a key inside of A will output it to B.

**To Reproduce**

1. Run the following basalt snippet:
```lua
local A = main_frame:addInput("A")
	:setPosition(1, 1)
	:setSize(20, 1)
	:show()

local B = main_frame:addInput("B")
	:setPosition(1, 2)
	:setSize(20, 1)
	:show()

A:onKey(function(self, event, key)
	B:setFocus()
end)
```
2. Click on Input A, and press 'a'.

The output 'a' will be produced to B.

**Expected behavior**

Again... I'm now sure if this is a bug, or expected behaviour. However, I expected the 'a' to appear in the first input, and _then_ the focus be set to B.

**Screenshots**

https://user-images.githubusercontent.com/43142209/194728378-e883cf94-82d6-4962-ac02-7611494d73df.mp4

**Checklist**

[x] I am running the latest version.
Tick the box if you are running the latest version!

**Comment by NoryiE** [comment]
Hey! This isn't a bug. :setFocus sets the object immediatley as the focused object. The reason why your custom onKey event handler happens before the inputbox's key event handler is because of the following code:
```lua
A:onKey(function(self, event, key)
   if(key==keys.a)then
      return false
   end
end)
```
this code would make it impossible to write "a" into the inputbox. A possibility would be to create a delayed task:

```lua
A:onKey(basalt.schedule(function(self, event, key)
  sleep(0.1)
  B:setFocus()
end)
```
This code would wait 0.1s before changing the focus.
https://basalt.madefor.cc/#/objects/Basalt/schedule

**Comment by luiz00martins** [comment]
I'd also be fine with the key not being recorded by any of them. My major problem is that the key 'passes over' to B.

Is there a way to avoid that?

**Comment by NoryiE** [comment]
```lua
A:onKey(function(self, event, key)
  B:setFocus()
  return false
end)
```
This would make it impossible to write into the input "A" - i am not sure if that's what you want.

**Comment by luiz00martins** [comment]
Not exactly. What I want is to capture a specific key, say `.`, and move to the next input after `.`.

However, using this code:
```lua
A:onKey(function(self, event, key)
	if key == 46 then
		B:setFocus()
	end
end)
```

ends up with the dot in B. Again, the problem is not that the output does or doesn't go to A. The problem is that the output goes to B:

https://user-images.githubusercontent.com/43142209/194730095-41655867-ce9d-4d46-9d22-4daf4a5f2da2.mp4

The output I expected was `"This is a sentence."` in A, and nothing in B. If the code had a `return false`, I would expect the output to be `"This is a sentence"` in A, and nothing in B.

The `sleep` solution feels... suboptimal. I feel like the output should just not be recasted to B (i.e. instead of outputting to the currently focused object, it should output to the target object of the keypress). More specifically:
 - If `return == false`, then no output should be produced in either.
 - If `return ~= false`, then the output should be produced to A, not to B.

**Comment by NoryiE** [comment]
Hello, thank you very much. I understand now why this is happening. Basalt 1.6.3 has the fix for it - i seperated the char events from the key events, this menas you would need to use a :onChar() event instead of :onKey().

If you are curious on how the events work:
I am using the cc:tweaked event "char" for changing the input. The problem here was the key event always happens before the char event, and i decided one time to call both, the key and the char event when someone uses :onKey(f) which means in your case, you click the ".", the key loop runs, you make the b-input to be the focused one, then the char event loop runs and it writes the . into the b-input (because its focused).

**Comment by luiz00martins** [comment]
Just checked. Everything is working as intended now!

Thank you for the quick fix, and thank you for the compliment! I'm using basalt for a personal project, so expect to hear from me again! Cheers
