### ISSUE TITLE
feature: Better image handling

### ISSUE THREAD

**Issue by Apethesis** [Pyroxenium/Basalt#41]
**Is your feature request related to a problem? Please describe.**
I am frustrated cause its difficult to add support for another image format to Basalt (cimg2 in my case).

**Describe the solution you'd like**
I would like for there to be some kind of more modular way of handling images, perhaps with a separate library.

**Describe alternatives you've considered**
Modifying most Basalt code just so it might work.

**Comment by NoryiE** [comment]
It may not be necessary to add additional image formats if there is no significant benefit over existing ones. Bimg has become the primary image format for advanced image functionality in CC. Within basalt, bimg is always used internally, which means that in your case, you will need to convert cimg2 to bimg in order to be able to load cimg2 files. You can find the image library where changes need to be made here: https://github.com/Pyroxenium/Basalt/blob/master/Basalt/libraries/images.lua#L28
