### ISSUE TITLE
feature: Move The Examples From Frame To A Seperate Area For Examples

### ISSUE THREAD

**Issue by finnaminope** [Pyroxenium/Basalt#51]
**Is your feature request related to a problem? Please describe.**
It Is Extremely Annoying when I Have To Go To The Frame Section In The Docs To Find Examples And New Users Would Not Know Where To Find Them

**Describe the solution you'd like**
I Think The Examples Should Be Moved From The Frame Section To Somewhere Else

**Describe alternatives you've considered**
I have Considered Adding Something To Tell The User Where The Examples Are But I Think It Would Still Be Too Hard To Find

**Additional context**
![image](https://user-images.githubusercontent.com/91102755/227793538-ce43e6e1-8968-4019-845f-4c10de241e1d.png)

**Comment by finnaminope** [comment]
Im Sorry If The Picture Looks Bad. I Used My Browser Tool

**Comment by NoryiE** [comment]
Helloooo, you are right. I made some bad decisions on the docs. My goal was to create a better example page for each object in the object's pages, i started with the frames (because it is the most important object) but never went further, the reason was because with basalt 1.7 some of the code will change, so i said to myself to wait with updating the docs until i release 1.7. While working on basalt 1.7 i ran into unexpected issues which i had to fix/rethink. This delayed the release by quite some time. It's almost done (xml isn't finished). After the release i will update the docs - ofc one of my bigger goal is to make it as easy to understand as possible. Thanks for your input!
